### ISSUE TITLE
If I show my players a journal entry, it pops up in their popped out window

### ISSUE THREAD

**Issue by algnc** [kakaroto/fvtt-module-popout#20] opened 2020-07-26 12:36 UTC
I didn't get them to do a screenshot...but if I show my players a journal entry, they were saying it showed up in their Popped out window too.

**Comment by kakaroto** [comment] 2020-07-26 22:00
That's normal and expected. Each popout window is a duplicate of the actual VTT with the canvas and sidebar hidden.

**Closed by kakaroto** 2020-07-26 22:00 UTC
