### ISSUE TITLE
Duplicate "Pop out!" button on token window

### ISSUE THREAD

**Issue by Oromis** [kakaroto/fvtt-module-popout#2] opened 2019-12-18 10:33 UTC
Great module, really useful!

Just a minor annoyance: I have two identical "Pop out!" buttons on my actor sheets:

![image](https://user-images.githubusercontent.com/1381990/71078706-31a01680-218a-11ea-8080-5c902b944dd5.png)

**Comment by kakaroto** [comment] 2020-01-16 22:20
I know I've seen this, I also know I've fixed it, but your report is from one month after the last release, so I don't know if I did fix it or if I just couldn't reproduce the problem anymore. I've reviewed the code and I don't know how it could happen. I also improved things so there's even less risk of it happening, so closing for now.
If you still get the issue, please re-open it, I should now receive notifications for it.
Thanks.

**Closed by kakaroto** 2020-01-16 22:20 UTC
